# Generated by Django 6.0 on 2026-06-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_hiretalent'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='willing_to_relocate',
            field=models.BooleanField(default=False),
        ),
    ]
